### ISSUE TITLE
Latitude & Longitude misplacement of decoding ParsePolygon.

### ISSUE THREAD

**Issue by nomoneynohoney** [netreconlab/Parse-Swift#115]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description

Latitude & Longitude misplacement of decoding ParsePolygon: The order of the element in polygon is [lat, lon], the current decoding order is misplacement. The error is found at ParsePolygon: 108.

### Steps to reproduce

Use [[25.1234, 121.4567], [24.321, 121.1234], [22.11, 101.321]] as test polygon data in database. Caused a decoding error.

### Actual Outcome

error.

### Expected Outcome

a sequence of GeoPoint.

### Environment

5.7.0

Client
- Parse Swift SDK version: `5.7.0`
- Xcode version: `14.3.1`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `13.4`

Server
- Parse Server version: `6.2.0`
- Operating system: `Ubuntu 20.04 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Linode`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `6.0.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Linode`

**Comment by cbaker6** [comment]
Can you post the actual error returned from the server.

What happens when you run the Playground code? https://github.com/netreconlab/Parse-Swift/blob/57ccb4be70feedbc289db65d4ff5732c3b9ef5ec/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L398-L415

**Comment by nomoneynohoney** [comment]
ParsePolygon.swift, line: 108. the order of a point in the polygon should be [lat, lon].

**Comment by nomoneynohoney** [comment]
There won't be error, because the value is decodable. but the order is misplaced, so if u really generate a sequence of coordinates, save into db, then use ParseSwift to decode it and place them back on map. you will find the error.

**Comment by cbaker6** [comment]
> There won't be error, because the value is decodable. but the order is misplaced, so if u really generate a sequence of coordinates, save into db, then use ParseSwift to decode it and place them back on map. you will find the error.

You stated it caused a decoding error, this is the error I was referring to:
> Use [[25.1234, 121.4567], [24.321, 121.1234], [22.11, 101.321]] as test polygon data in database. Caused a decoding error.


My tests show that the current implementation is correct (for Postgres and Mongo). The server needs `ParsePolygon` coordinates to be encoded as `(longitude, latitude)`, not `(latitude, longitude)` in order to use `ParsePolygon` for queries ~~and saved objects~~. On the other hand, when using `ParseGeoPoint`'s directly, the server needs encoding `(latitude, longitude)`. When you decode `ParsePolygon` it should always decode properly to `latitude` and `longitude` for each `ParseGeoPoint`. All of this can be seen in https://github.com/parse-community/parse-server/issues/4607 and the server-side tests: 
- https://github.com/parse-community/parse-server/blob/4ad08005086b86ea46ef7567513a212454074804/spec/ParsePolygon.spec.js#L499-L531
- https://github.com/parse-community/parse-server/blob/4ad08005086b86ea46ef7567513a212454074804/spec/MongoTransform.spec.js#L77-L123

I've updated the Playground examples so you can run them directly to test what I mentioned above: https://github.com/netreconlab/Parse-Swift/blob/80347b711be66796cd3eaeea087ef1441d18e3a3/ParseSwift.playground/Pages/7%20-%20GeoPoint.xcplaygroundpage/Contents.swift#L68-L113

Which results in the following output:

```bash
# Postgres
Saved location: {"__type":"GeoPoint","latitude":40,"longitude":-30}
Saved polygon: {"__type":"Polygon","coordinates":[[-30,35],[-35,42],[-20,42]]}
Saved polygon geopoints: [{"__type":"GeoPoint","latitude":35,"longitude":-30}, {"__type":"GeoPoint","latitude":42,"longitude":-35}, {"__type":"GeoPoint","latitude":42,"longitude":-20}]

# Mongo
Saved location: {"__type":"GeoPoint","latitude":40,"longitude":-30}
Saved polygon: {"__type":"Polygon","coordinates":[[-30,35],[-35,42],[-20,42]]}
Saved polygon geopoints: [{"__type":"GeoPoint","latitude":35,"longitude":-30}, {"__type":"GeoPoint","latitude":42,"longitude":-35}, {"__type":"GeoPoint","latitude":42,"longitude":-20}]
```

The following test was improved to ensure all of the aforementioned is maintained: https://github.com/netreconlab/Parse-Swift/blob/2688192c55667fd32651f11b72b54f9fe57259f7/Tests/ParseSwiftTests/ParsePolygonTests.swift#L77-L88

**Comment by cbaker6** [comment]
It looks like there may be a small bug here as the server handles saved polygons and queried polygons differently. Still investigating...

See #118
