### ISSUE TITLE
Saving Installation with device token fails.

### ISSUE THREAD

**Issue by Aziz-AnyDesk** [netreconlab/Parse-Swift#29]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description
Saving Installation object with device token for remove notification fails after second and consequent app launches with error: ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "objectId", intValue: nil) ("objectId").

### Steps to reproduce

```
import Foundation

struct DeviceInstallation: ParseInstallation {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: AclObject?
    var originalData: Data?

    var installationId: String?
    var deviceType: String?
    var deviceToken: String?
    var badge: Int?
    var timeZone: String?
    var channels: [String]?
    var appName: String?
    var appIdentifier: String?
    var appVersion: String?
    var parseVersion: String?
    var localeIdentifier: String?

    var userId: String?

    func merge(with object: Self) throws -> Self {
        var updated = try mergeParse(with: object)
        if updated.shouldRestoreKey(\.userId,
                                     original: object) {
            updated.userId = object.userId
        }
        return updated
    }
}

// This function is called inside AppDelete - didRegisterForRemoteNtoficationsWithDeviceToken
public func save(deviceToken token: Data, completion: @escaping (Swift.Result<DeviceInstallation, ErrorObject>) -> Void) {
        var installation = DeviceInstallation.current
        installation?.setDeviceToken(token)
        installation?.channels = ["test_channel"]
        installation?.userId = ParseUser.current?.objectId
        installation?.save(completion: completion)
}
```
    

### Actual Outcome
In first app launch it saves successfully but next consequent app launches and saving installation object for remote notification fail with error:  ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "objectId", intValue: nil) ("objectId").

### Expected Outcome
Should save device token successfully during every app launch for remote notifications to work properly.

Client
- Parse Swift SDK version: `14.6.2`
- Xcode version: `14.1`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `13.0.1`

Server
- Parse Server version: `3.6.0`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Shashido remote hosting provider`

**Comment by cbaker6** [comment]
Sever version `3.6.0` is extremely old and not supported by Parse. You can look through the [changes made on the server since your version](https://github.com/parse-community/parse-server/blob/alpha/changelogs/CHANGELOG_release.md#360) to see if someone addressed that issue. I suspect it's either a server issue or how you have your SDK configured. You can check through issues below to see if you can get it fixed:

- Older servers and configurations can produce similar problems to yours. You can see a thread related to Parse Server 4 on Back4App: https://github.com/parse-community/Parse-Swift/issues/313
- https://github.com/parse-community/Parse-Swift/issues/335#issuecomment-1023568621
- https://github.com/parse-community/Parse-Swift/issues/171#issuecomment-866034706

I recommend you try your code out in docker using the latest parse server version. You can see how to do this here: https://github.com/netreconlab/Parse-Swift/blob/main/CONTRIBUTING.md#swift-playgrounds

If you can replicate your issue on the latest server, then I'll take a further look. Note that I doubt this issue occurs with the latest server as I update the installation in my apps and haven't ran into this issue.

> Should save device token successfully during every app launch for remote notifications to work properly.

I also don’t believe `didRegisterForRemoteNtoficationsWithDeviceToken` gets called on every app launch if you are using it correctly. I believe the OS only calls this every so often. See more on [Apple’s documentation](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application?changes=_8)

**Comment by cbaker6** [comment]
Another suspicion is that you are calling `func save(deviceToken token: Data...)` before you initialize the SDK, so your `var installation = DeviceInstallation.current` isn't the current Installation from your Keychain. Since you are using `AppDelegate`, you should make sure you are initializing your SDK in `applicationDidFinishLaunching` or in `willFinishLaunchingWithOptions`. A similar issue happened with someone else here: https://github.com/parse-community/Parse-Swift/issues/335#issuecomment-1023568621

**Comment by cbaker6** [comment]
I tested this on the latest parse-server by modifying the following Playground and cannot replicate your issue:

https://github.com/netreconlab/Parse-Swift/blob/35a7fe9d4031f37f43486c73a4e05ec355a76c2a/ParseSwift.playground/Pages/6%20-%20Installation.xcplaygroundpage/Contents.swift#L16-L90

to:

```swift
/*: Save your first `customKey` value to your `ParseInstallation`.
    Performs work on background queue and returns to designated on
    designated callbackQueue. If no callbackQueue is specified it
    returns to main queue. Note that this may be the first time you
    are saving your Installation.
 */
var currentInstallation = Installation.current
currentInstallation?.deviceToken = "123"
currentInstallation?.save { results in

    switch results {
    case .success(let updatedInstallation):
        print("Successfully saved Installation to ParseServer: \(updatedInstallation)")
    case .failure(let error):
        print("Failed to update installation: \(error)")
    }
}

/*:
 Update your `ParseInstallation` `customKey` and `channels` values.
 Performs work on background queue and returns to designated on
 designated callbackQueue. If no callbackQueue is specified it
 returns to main queue. Using `.mergeable` or `set()`
 allows you to only send the updated keys to the
 parse server as opposed to the whole object.
 */
var installationToUpdate = Installation.current
installationToUpdate?.deviceToken = "456"
installationToUpdate?.customKey = "myCustomInstallationKey2"
installationToUpdate?.channels = ["newDevices"]
installationToUpdate?.save { results in

    switch results {
    case .success(let updatedInstallation):
        print("Successfully saved myCustomInstallationKey to ParseServer: \(updatedInstallation)")
    case .failure(let error):
        print("Failed to update installation: \(error)")
    }
}
```

I will be closing this out soon as it doesn't look like a Swift SDK issue...
